
const mongoose = require('mongoose');

const mandiRateSchema = new mongoose.Schema(
  {
    state: { type: String, required: true, trim: true },
    district: { type: String, required: true, trim: true },
    marketName: { type: String, required: true, trim: true }, // Mandi Name
    commodity: { type: String, required: true, trim: true },
    variety: { type: String, default: 'Other' },
    minPrice: { type: Number, required: true },
    maxPrice: { type: Number, required: true },
    modalPrice: { type: Number, required: true }, // Average market rate
    arrivalDate: { type: Date, required: true },

    // AI Price Prediction outputs (generated by Python microservice)
    predictedPrice15Days: [
      {
        date: Date,
        predictedPrice: Number,
        confidenceIntervalLower: Number,
        confidenceIntervalUpper: Number,
      },
    ],
    trendRecommendation: {
      type: String,
      enum: ['SELL_NOW', 'HOLD_5_DAYS', 'HOLD_10_DAYS', 'HIGH_DEMAND_EXPECTED'],
      default: 'SELL_NOW',
    },
  },
  { timestamps: true }
);

// Compound index to quickly fetch latest mandi price for a specific commodity in a district
mandiRateSchema.index({ district: 1, commodity: 1, arrivalDate: -1 });

module.exports = mongoose.model('MandiRate', mandiRateSchema);